### ISSUE TITLE
Coinbase - works fine for an hour then gets 'stuck' on Ask price

### ISSUE THREAD

**Issue by commonwealthgoods** [michaelgrosner/tribeca#197]
I have Coinbase set up and successfully trading.  After about an hour or so it seems to get 'stuck' on a price and has a single sell order at a price too high to fill and does not create any new orders.  I'm using Mode Top, BBO, and APmode off.  Running on OSX Sierra with the most up to date docker.  Restarting Tribeca solves the issue and it starts placing correctly priced orders again  Any suggestions?

**Comment by uxjulia** [comment]
Creating a docker volume seemed to fix this issue for me. You can create a volume with `docker volume create <volume-name>` and then in the `docker-compose.yml` file add the volume to the services. Your docker-compose.yml file should look something like this (replace 'yourVolumeName' with your chosen volume name):

```
version: '2'
services:
  tribeca:
    build:
      context: ./
    image: tribeca
    env_file:
      - ./env
    links:
      - tribeca-mongo
    ports:
      - "80:80"
    tty: true
    volumes:
      - yourVolumeName:/data
  tribeca-mongo:
    image: mongo
    restart: on-failure
    volumes:
      - yourVolumeName:/data/db
volumes:
  yourVolumeName:
   external: true
```
